#!/bin/bash

echo "📝 Supabase Auth URLs müssen manuell aktualisiert werden"
echo ""
echo "Gehe zu:"
echo "https://supabase.com/dashboard/project/yjjauvmjyhlxcoumwqlj/auth/url-configuration"
echo ""
echo "Site URL setzen:"
echo "https://mimicheck.ai"
echo ""
echo "Redirect URLs hinzufügen (alle):"
echo "https://mimicheck.ai/auth"
echo "https://app.mimicheck.ai/auth-bridge"
echo "https://app.mimicheck.ai/onboarding"
echo "https://app.mimicheck.ai/dashboard"
echo "https://mimicheck-landing.vercel.app/auth"
echo "https://mimicheck.vercel.app/auth-bridge"
echo "http://localhost:3000/auth"
echo "http://localhost:8005/auth-bridge"
echo ""
echo "✅ Dann speichern!"
